# Generated by Django 3.1.2 on 2020-11-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwKot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=100, verbose_name='Расположение')),
            ],
        ),
        migrations.CreateModel(
            name='HwTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_info', models.CharField(max_length=100, verbose_name='Железо')),
            ],
        ),
        migrations.CreateModel(
            name='WwwTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('note', models.TextField(blank=True, verbose_name='Заметки')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwKot.deptbl')),
                ('hw_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwKot.hwtbl')),
            ],
        ),
        migrations.DeleteModel(
            name='WwwDB',
        ),
    ]
